# This is a basic workflow to help you get started with Actions

name: update-readme

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify the Python version you need
      - name: Install dependencies
        run: pip install -r requirements.txt  # If you have any dependencies
      - name: Execute Mermaid Converter script
        run: python scripts/Mermaid_Converter.py  # Execute your Python script
      - name: Execute gen_DCAT-APsLinkMLviaCSV script
        run: python scripts/gen_DCAT-APsLinkMLviaCSV.py  # Execute your Python script
      - name: Move YAML file to main repo directory
        run: mv 'DCAT_AP_via_CSV.yaml' ../
      - name: Run the script
        run: python scripts/update_readme.py
      - name: Commit files
        #if: "! git status --short" # check if there are changes to commit
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "action@github.com"
          git add '*.md' DCAT_AP_via_CSV.yaml
          # git add tags/*.md
          # Thanks for the trick, ChatGPT!
          if git diff-index --quiet HEAD --; then
            echo "changes_to_push=false" >> $GITHUB_ENV
          else
            git commit -m "Updated TOC"
            echo "changes_to_push=true" >> $GITHUB_ENV
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
